### ISSUE TITLE
Wallet.dat encrypted, wallet.dat crash (any version V2.1, V2.2.2.1)?

### ISSUE THREAD

**Issue by CloakProjectDev** [CloakProject/CloakCoin#17]
- wallet.dat cannot be decrypted with the passphrase any more
- blockchain is synced up to date
- wallet.dat backup also does not work

- using a wallet.dat backup with a bockchain that needs syncing for the past weeks, wallet.dat can be decrypted with the passphrase, no issues.
- After full sync, wallet.dat works with fully synced bockchain on other computers again.

Assumption: a certain configuration affects the encryption together with the blockchain. In wallet.dat there are tx received with Enigma (latest Txs).

**Comment by anorakthagreat** [comment]
This issue was related to a specific wallet.dat file (probably damaged/corrupted). Also, it's misleading and not clear from the description, but the keys couldn't be decrypted, that wallet.dat file was not actually encrypted (on exit option). Not entirely sure about how syncing blocks can affect keys encryption/decryption - possibly a coincidence with something else (different cause). Closing until issue can be repeated/verified.
